// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA1Bj4TOkUBeGE1JaHIwRPIkQICRcqoSo',
    appId: '1:278750220946:web:a68bbcffe0766209c8cc4b',
    messagingSenderId: '278750220946',
    projectId: 'notes-a25b0',
    authDomain: 'notes-a25b0.firebaseapp.com',
    storageBucket: 'notes-a25b0.appspot.com',
    measurementId: 'G-JPV9TQJ45T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3IqYsAWurkOcFlZ4HXHRDacxJIwOb5LU',
    appId: '1:278750220946:android:9a43d203ec2016ecc8cc4b',
    messagingSenderId: '278750220946',
    projectId: 'notes-a25b0',
    storageBucket: 'notes-a25b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw22USvhLTkHlYOur_X6dU0jlirkGGlaA',
    appId: '1:278750220946:ios:bf45943cb9a17f5bc8cc4b',
    messagingSenderId: '278750220946',
    projectId: 'notes-a25b0',
    storageBucket: 'notes-a25b0.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw22USvhLTkHlYOur_X6dU0jlirkGGlaA',
    appId: '1:278750220946:ios:f81521edb856f441c8cc4b',
    messagingSenderId: '278750220946',
    projectId: 'notes-a25b0',
    storageBucket: 'notes-a25b0.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
